---
title: "gcc_phase_tri_plot_internal"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{gcc_phase_tri_plot_internal}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(soundlocalization)
library(tidyverse)
library(lubridate)
```


```{r}
files <- list(
  system.file("extdata", "Grabacion_2_andrea.wav", package = "soundlocalization"),
  system.file("extdata", "Grabacion_1_joaco.wav", package = "soundlocalization"),
  system.file("extdata", "Grabacion_1_cande.wav", package = "soundlocalization"),
  system.file("extdata", "Grabacion_3_luciano.wav", package = "soundlocalization")
)
labels = c("Andrea", "Joaco", "Candela", "Luciano")
geo_locations = rbind(
  geo_coordinates(
    lat = -34.61410605441556,
    lon = -58.38404404725583
  ),
  geo_coordinates(
    lat = -34.614103295104634,
    lon = -58.3839950969408
  ),
  geo_coordinates(
    lat = -34.6140999839314,
    lon = -58.383942123312224
  ),
  
  geo_coordinates(
    lat = -34.61409722462029,
    lon = -58.38389920796756
  )
)
time_of_recording = ymd_hm("2022-09-03 10:52", tz = "America/Buenos_Aires")
rec<-recordings(files = files,
                       labels = labels,
                       geo_locations = geo_locations, 
                       time_of_recording = time_of_recording)
a_recordings<-align_recordings(rec)
```


Lets obtain the cross correlation data

```{r}
  d=gcc_phase_data(rec = a_recordings,t_start =  118,t_end = 120.8,min_freq = 500,max_freq = 6000,lag_window_in_meters = 20, remove_if_z_is_greater_than = 5)
```

