---
title: "geo_location_internal"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{geo_location_internal}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(soundlocalization)
```

we convert geografic coordinates to local coordinates

```{r}
geo_locations=rbind(c(lat=-34.61410605441556,
                                lon= -58.38404404725583),
                c(lat=-34.614103295104634,lon=  -58.3839950969408),
                c(lgeat=-34.6140999839314, lon= -58.383942123312224),
                c(lat=-34.61409722462029, lon= -58.38389920796756))
geo_locations
```

```{r}
local=geo_to_local(origin=geo_locations[1,],geo_locations[2,],geo_locations)
local
```

Lets see if we recover the initial geo_coordinates
```{r}
local_to_geo(geo_locations[1,],geo_locations[2,],local[,1],local[,2])->c
c
```

```{r}
local2=geo_to_local(origin=geo_locations[1,],geo_locations[2,],c)
local2-local

```

